# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram-Slack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'AlamofireNetworkActivityIndicator'

  # Pods for Instagram-Slack

end
